---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelinespringbootdemo
  namespace: devops-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelinespringbootdemo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pipelinespringbootdemo
    spec:
      #nodeName: change_me_to_Node_name
      containers: 
        - image: 192.168.8.136:9443/springbootproject/anapsix/alpine-java:22
          imagePullPolicy: IfNotPresent
          name: pipelinespringbootdemo
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          ports:
          - name: http
            containerPort: 8082
            protocol: TCP
      imagePullSecrets:
        - name: reg-secret

---

apiVersion: v1
kind: Service
metadata:
  name: pipelinespringbootdemo-service
  namespace: devops-namespace
spec:
  type: NodePort
  selector:
    app: pipelinespringbootdemo
  ports:
    - name: http
      nodePort: 32082
      protocol: TCP
      port: 8082
      targetPort: 8082
